# Generated by Django 3.2.13 on 2022-04-25 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Core Value Name')),
            ],
            options={
                'db_table': 'core_value',
            },
        ),
        migrations.CreateModel(
            name='OptionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Option Choice Order')),
                ('value', models.CharField(max_length=100, unique=True, verbose_name='Option Choice Value')),
            ],
            options={
                'db_table': 'option_choice',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='OptionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Option Group Name')),
                ('options', models.ManyToManyField(to='question.OptionChoice', verbose_name='List of Option Choices')),
            ],
            options={
                'db_table': 'option_group',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250, verbose_name='Question Text')),
                ('subtext', models.CharField(max_length=250, verbose_name='Question Subtext')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'Multiple Choice')], default=0, verbose_name='Question Type')),
                ('required', models.BooleanField(default=True, verbose_name='Required')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Question Order')),
                ('core_value', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='question.corevalue', verbose_name='Core Value')),
                ('option_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='question.optiongroup', verbose_name='Related Option Group')),
            ],
            options={
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_answer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='question.optionchoice', verbose_name='Answer from Choices')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.question', verbose_name='Related Question')),
            ],
            options={
                'db_table': 'answer',
            },
        ),
    ]
