# Generated by Django 3.2.13 on 2022-04-25 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250, verbose_name='Section Description')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'Project'), (1, 'Team Member'), (2, 'Project Manager'), (3, 'Client')], verbose_name='Section Type')),
                ('questions', models.ManyToManyField(to='question.Question', verbose_name='Related Questions')),
            ],
            options={
                'db_table': 'feedback_section',
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Template Name')),
                ('sections', models.ManyToManyField(to='feedback.FeedbackSection', verbose_name='Feedback Sections')),
            ],
            options={
                'db_table': 'template',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250, verbose_name='Feedback Description')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Feedback Completed')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Feedback Start Date')),
                ('end_date', models.DateField(verbose_name='Feedback End Date')),
                ('projects', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project.project', verbose_name='Related Project')),
                ('sections', models.ManyToManyField(to='feedback.FeedbackSection', verbose_name='Feedback Sections')),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
    ]
