# Generated by Django 3.2.13 on 2022-04-25 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Client Name')),
            ],
            options={
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Project Name')),
                ('description', models.CharField(max_length=200, verbose_name='Project Description')),
                ('icon', models.URLField(verbose_name='Project Icon')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.client', verbose_name='Project Client')),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Project Members')),
                ('project_manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_manager', to=settings.AUTH_USER_MODEL, verbose_name='Project Manager')),
            ],
            options={
                'db_table': 'project',
            },
        ),
    ]
